---
- name: Install php-fpm
  apt: name=php5-fpm state=present

- name: Copy across new php-fpm pool config
  template:
    src=php-fpm/www.conf.j2
    dest=/etc/php5/fpm/pool.d/www.conf
  notify:
    - restart php-fpm