---
- name: Clone Symfony2 standard edition
  git: repo=https://github.com/symfony/symfony-standard.git
       dest=/vagrant/symfony-standard

- name: Copy across new parameters.yml
  template:
    src=symfony/symfony_parameters.yml.j2
    dest=/vagrant/symfony-standard/app/config/parameters.yml

- stat: path=/vagrant/symfony-standard/vendor
  register: p

- name: Install Symfony2 project dependencies
  shell: cd /vagrant/symfony-standard && composer install
  when: p.stat.isdir is not defined